name: test-checkout
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
    #  repository-projects: write 
    steps:
      - uses: actions/checkout@main
  noperms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
