name: actions-checkout-main-ghr
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
  noperms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
