name: compare-runners
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  shr:
    runs-on: self-hosted
    steps:
      - uses: devops-testbed/checkout@main
  ghr:
    runs-on: ubuntu-latest
    steps:
      - uses: devops-testbed/checkout@main
  shr-fix:
    runs-on: self-hosted
    steps:
      - uses: devops-testbed/checkout@main
        with:
          clean: true
          submodules: false
  shr-fix2:
    runs-on: self-hosted
    steps:
      - uses: devops-testbed/checkout@main
        with:
          clean: true
  shr-fix3:
    runs-on: self-hosted
    steps:
      - uses: devops-testbed/checkout@main
        with:
          submodules: true
