name: compare-runners
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  shr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
  ghr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
